# Step 1 – Use Python 3.11 as base image
FROM python:3.11

# Step 2 – Set working directory inside the container
WORKDIR /app

# Step 3 – Copy all project files into the container
COPY . .

# Step 4 – Set the default command to run your CLI
CMD ["python", "main.py"]
