name: Build and Deploy to ACI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_REGISTRY: cloudlabacr11103.azurecr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Validate AZURE_CREDENTIALS
      run: |
        echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -e '.clientId and .clientSecret and .tenantId' || exit 1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_REGISTRY }}
        username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
        password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

    - name: Build the Docker image
      run: |
        docker build -t ${{ env.ACR_REGISTRY }}/phonebook-app:${{ github.sha }} \
                     -t ${{ env.ACR_REGISTRY }}/phonebook-app:latest ./Contacts

    - name: Push the Docker image
      run: |
        docker push ${{ env.ACR_REGISTRY }}/phonebook-app:${{ github.sha }}
        docker push ${{ env.ACR_REGISTRY }}/phonebook-app:latest

  deploy-to-aci:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Delete existing ACI if exists
      run: |
        az container delete --resource-group CLOUDLAB-DEV-RG --name phonebook-container --yes || true

    - name: Deploy to Azure Container Instance
      run: |
        az container create \
          --resource-group CLOUDLAB-DEV-RG \
          --name phonebook-container \
          --image ${{ env.ACR_REGISTRY }}/phonebook-app:latest \
          --registry-login-server ${{ env.ACR_REGISTRY }} \
          --registry-username ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }} \
          --registry-password ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }} \
          --dns-name-label phonebook-app \
          --location westeurope \
          --os-type Linux \
          --cpu 1 \
          --memory 1.5 \
          --ports 80
