name: Build and Deploy to ACI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI Login to ACR
      run: |
        az acr login --name cloudlabacr11103

    - name: Build the Docker image
      run: |
        docker build -t cloudlabacr11103.azurecr.io/phonebook-app:latest ./Contacts

    - name: Push the Docker image
      run: |
        docker push cloudlabacr11103.azurecr.io/phonebook-app:latest

  deploy-to-aci:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Instance
      run: |
        az container create \
          --name ${{ secrets.ACI_NAME }} \
          --resource-group ${{ secrets.ACI_RG }} \
          --image cloudlabacr11103.azurecr.io/phonebook-app:latest \
          --registry-login-server cloudlabacr11103.azurecr.io \
          --location ${{ secrets.ACI_LOCATION }} \
          --dns-name-label cloudlab-${{ github.run_number }} \
          --ports 80 \
          --os-type Linux
